name: task_tracker
description: A Flutter application for tracking tasks.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  flutter_hooks: ^0.18.5
  animations: ^2.0.6
  flutter_staggered_grid_view: ^0.6.2
  flutter_animate: ^4.0.0
  shared_preferences: ^2.0.15
  google_fonts: ^4.0.3
  flutter_colorpicker: ^1.0.3
  sqflite_common_ffi: ^2.1.0  # Добавлено


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
